### ISSUE TITLE
Softmax benchmark

### ISSUE THREAD

**Issue by mahmoodn** [utcs-scea/altis#17]
Hi
I don't see DNN workloads in level 0, 1 and 2 folders. I mean softmax,  activation and ...
Where should I look exactly?

**Comment by BDHU** [comment]
They were moved to the deprecated branch and should be inside the darknet directory at level2

**Comment by mahmoodn** [comment]
I cloned that branch and ran setup.sh. However, it seems that not enough. I also switched to src/cuda/level2/darknet and executed make and got this error

```
./src/convolutional_layer.c:167:13: error: ‘CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT’ undeclared (first use in this function)
  167 |             CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT,
```

**Comment by BDHU** [comment]
Without knowing your execution environment, the answers here are merely speculative. This error is likely caused by CUDA 11 and cuDNN  8. It was tested with CUDA 9 and 10 with cuDNN 7 before and it's likely not supported by newer versions. There might be plans to address those issues but downgrading the CUDA and cuDNN might solve the problem.

**Comment by mahmoodn** [comment]
Yes that was CUDA 11.2. Thanks.
